version: 3

tasks:
  ai:r1:
    cmds:
      - aider --architect --model openrouter/deepseek/deepseek-r1 --editor-model openrouter/anthropic/claude-3.5-sonnet

  ai:gemini:
    cmds:
      - aider --model openrouter/google/gemini-2.5-pro-preview --edit-format diff-fenced

  ai:
    desc: Run Anthropic assistant
    cmds:
      - aider --model openrouter/anthropic/claude-sonnet-4
